# Generated by Django 5.2.8 on 2025-11-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase3', '0004_alter_customers_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
